CREATE TABLE articleLikes (
  articleID INT NOT NULL,
  userID INT NOT NULL,
  FOREIGN KEY (articleID) REFERENCES articles (ID) ON DELETE CASCADE,
  FOREIGN KEY (userID) REFERENCES users (ID) ON DELETE CASCADE,
  PRIMARY KEY (articleID, userID)
);
